name: "Ponicode Unit Test"
description: "Writes unit tests for all your repository"
branding:
    icon: "align-justify"
    color: "orange"
inputs:
    repoPath:
        description: "Path of repo to generate unit tests for"
        required: true
        default: "./"
    authToken:
        description: "Ponicode token to use Ponicode API"
        required: true
        default: ""
    changedFilesOnly:
        description: "Boolean. Enter true to generate test for changes since last repo or enter false if you want to generate for the whole repo"
        required: false
        default: "false"
    coverageJsonPath:
        description: "String. Enter the path to your coverage-final.json (Example: coverage/coverage-final.json)"
        required: false
runs:
    using: "docker"
    image: "Dockerfile"
    args:
        - ${{ inputs.repoPath }}
        - "--auth-token"
        - ${{ inputs.authToken }}
        - "--changed-files-only"
        - ${{ inputs.changedFilesOnly}}
        - "--coverage-json-path"
        - ${{ inputs.coverageJsonPath}}
