name: 'Ponicode Unit Test'
description: 'Raise high coverage in seconds with automatic Unit-Tests generation'
branding:
  icon: 'align-justify'  
  color: 'orange'
inputs: 
  repoUrl:
    description: 'String: URL of the repo to be processed'
    required: true
  ponicodeUtToken:
    description: 'String: Ponicode UT user token from Github Secrets'
    required: true
  githubToken:
    description: 'GitHub token to generate some comments into the PR'
    required: true
  impactedFiles:
    description: 'String[]: List of the files updated in the PR'
    required: true
  branch:
    description: 'String: branch on which the PR applies'
    required: true
    default: 'master'
runs:
  using: 'node12'
  main: 'release/index.js'
  